export const DEFAULT_KEYBOARD_SHORTCUTS = [
    { combination: 'ctrl+z', actionId: 'undo', description: 'Отменить действие', preventDefault: true },
    { combination: 'ctrl+я', actionId: 'undo', description: 'Отменить действие (рус)', preventDefault: true },
    { combination: 'ctrl+shift+z', actionId: 'redo', description: 'Повторить действие', preventDefault: true },
    { combination: 'ctrl+shift+я', actionId: 'redo', description: 'Повторить действие (рус)', preventDefault: true },
    { combination: 'ctrl+y', actionId: 'redo', description: 'Повторить действие (альтернативный)', preventDefault: true },
    { combination: 'ctrl+н', actionId: 'redo', description: 'Повторить действие (рус альт)', preventDefault: true },
    { combination: 'ctrl+a', actionId: 'select-all', description: 'Выделить все', preventDefault: true },
    { combination: 'ctrl+ф', actionId: 'select-all', description: 'Выделить все (рус)', preventDefault: true },
    { combination: 'ctrl+c', actionId: 'copy', description: 'Копировать', preventDefault: true },
    { combination: 'ctrl+с', actionId: 'copy', description: 'Копировать (рус)', preventDefault: true },
    { combination: 'ctrl+v', actionId: 'paste', description: 'Вставить', preventDefault: false },
    { combination: 'ctrl+м', actionId: 'paste', description: 'Вставить (рус)', preventDefault: false },
    { combination: ']', actionId: 'layer-bring-to-front', description: 'На передний план', preventDefault: true },
    { combination: 'ctrl+]', actionId: 'layer-bring-forward', description: 'Перенести вперёд', preventDefault: true },
    { combination: '[', actionId: 'layer-send-to-back', description: 'На задний план', preventDefault: true },
    { combination: 'ctrl+[', actionId: 'layer-send-backward', description: 'Перенести назад', preventDefault: true },
    { combination: 'delete', actionId: 'delete', description: 'Удалить объект', preventDefault: true },
    { combination: 'backspace', actionId: 'delete', description: 'Удалить объект', preventDefault: true },
    { combination: 'escape', actionId: 'escape', description: 'Отменить выделение', preventDefault: true },
    { combination: 'v', actionId: 'tool-select', description: 'Выбрать инструмент выделения' },
    { combination: 'м', actionId: 'tool-select', description: 'Выбрать инструмент выделения (рус)' },
    { combination: 't', actionId: 'tool-text', description: 'Выбрать инструмент текста' },
    { combination: 'е', actionId: 'tool-text', description: 'Выбрать инструмент текста (рус)' },
    { combination: 'r', actionId: 'tool-frame', description: 'Выбрать инструмент рамки' },
    { combination: 'к', actionId: 'tool-frame', description: 'Выбрать инструмент рамки (рус)' },
    { combination: 'arrowup', actionId: 'move-up', description: 'Переместить вверх', preventDefault: true },
    { combination: 'arrowdown', actionId: 'move-down', description: 'Переместить вниз', preventDefault: true },
    { combination: 'arrowleft', actionId: 'move-left', description: 'Переместить влево', preventDefault: true },
    { combination: 'arrowright', actionId: 'move-right', description: 'Переместить вправо', preventDefault: true },
];
