# .github/workflows/moodboard-deploy.yml
name: Moodboard - Test, Build & Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: moodboard-dist
        path: dist/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: moodboard-dist
        path: dist/
    
    - name: Deploy to TimeWeb.Cloud server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.TIMEWEB_HOST }}
        username: ${{ secrets.TIMEWEB_USERNAME }}
        key: ${{ secrets.TIMEWEB_SSH_KEY }}
        script: |
          echo "🚀 Starting Moodboard deployment..."
          
          # Создаем директорию если её нет
          sudo mkdir -p /var/www/moodboard
          sudo chown -R www-data:www-data /var/www/moodboard
          
          # Останавливаем moodboard если запущен
          if pm2 list | grep -q "moodboard"; then
            pm2 stop moodboard
          fi
          
          # Переходим в директорию moodboard
          cd /var/www/moodboard
          
          # Получаем последние изменения
          git fetch origin
          git reset --hard origin/main
          
          # Копируем собранные файлы
          echo "📦 Copying built files..."
          sudo rm -rf dist/
          sudo cp -r /tmp/dist/ .
          sudo chown -R www-data:www-data dist/
          
          # Создаем бэкап текущей версии
          if [ -d "dist" ]; then
            echo "💾 Creating backup..."
            sudo mkdir -p /var/www/backups
            sudo tar -czf "/var/www/backups/moodboard_backup_$(date +%Y%m%d_%H%M%S).tar.gz" dist/
          fi
          
          echo "✅ Moodboard deployment completed!"
          
          # Уведомляем miro о необходимости обновления
          echo "🔄 Moodboard updated, consider updating miro project"
